const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";

const ONLINE_USERS = "ONLINE_USERS";

// Message lifecycle
const MESSAGE_EDITED = "MESSAGE_EDITED";
const MESSAGE_DELETED = "MESSAGE_DELETED";
const MESSAGE_SEEN = "MESSAGE_SEEN";

// Sent back to the author of a socket message so an optimistic bubble can be
// reconciled with its persisted _id (or rolled back on failure).
const MESSAGE_ACK = "MESSAGE_ACK";
const MESSAGE_ERROR = "MESSAGE_ERROR";

export {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  START_TYPING,
  STOP_TYPING,
  CHAT_JOINED,
  CHAT_LEAVED,
  ONLINE_USERS,
  MESSAGE_EDITED,
  MESSAGE_DELETED,
  MESSAGE_SEEN,
  MESSAGE_ACK,
  MESSAGE_ERROR,
};
